included:
  - .
excluded:
  - Pods
  - Carthage
  - Build

opt_in_rules:
  - empty_count
  - force_cast
  - force_try
  - trailing_whitespace
  - vertical_whitespace
  - switch_case_alignment

disabled_rules:
  - line_length
  - function_body_length
  - trailing_whitespace
  - vertical_whitespace

# Настройки для конкретных правил
force_cast:
  severity: warning
